/**
 * Country codes for phone selector — kebab-case ISO codes for the flag emoji + dial codes.
 * Curated list of top countries; full set still selectable via dropdown.
 */
export const COUNTRIES = [
  { iso: "IN", dial: "+91",  name: "India",          flag: "🇮🇳" },
  { iso: "US", dial: "+1",   name: "United States",  flag: "🇺🇸" },
  { iso: "GB", dial: "+44",  name: "United Kingdom", flag: "🇬🇧" },
  { iso: "AE", dial: "+971", name: "UAE",            flag: "🇦🇪" },
  { iso: "CA", dial: "+1",   name: "Canada",         flag: "🇨🇦" },
  { iso: "AU", dial: "+61",  name: "Australia",      flag: "🇦🇺" },
  { iso: "DE", dial: "+49",  name: "Germany",        flag: "🇩🇪" },
  { iso: "FR", dial: "+33",  name: "France",         flag: "🇫🇷" },
  { iso: "ES", dial: "+34",  name: "Spain",          flag: "🇪🇸" },
  { iso: "IT", dial: "+39",  name: "Italy",          flag: "🇮🇹" },
  { iso: "NL", dial: "+31",  name: "Netherlands",    flag: "🇳🇱" },
  { iso: "BR", dial: "+55",  name: "Brazil",         flag: "🇧🇷" },
  { iso: "MX", dial: "+52",  name: "Mexico",         flag: "🇲🇽" },
  { iso: "JP", dial: "+81",  name: "Japan",          flag: "🇯🇵" },
  { iso: "KR", dial: "+82",  name: "South Korea",    flag: "🇰🇷" },
  { iso: "SG", dial: "+65",  name: "Singapore",      flag: "🇸🇬" },
  { iso: "PH", dial: "+63",  name: "Philippines",    flag: "🇵🇭" },
  { iso: "ID", dial: "+62",  name: "Indonesia",      flag: "🇮🇩" },
  { iso: "PK", dial: "+92",  name: "Pakistan",       flag: "🇵🇰" },
  { iso: "BD", dial: "+880", name: "Bangladesh",     flag: "🇧🇩" },
  { iso: "NG", dial: "+234", name: "Nigeria",        flag: "🇳🇬" },
  { iso: "ZA", dial: "+27",  name: "South Africa",   flag: "🇿🇦" },
  { iso: "KE", dial: "+254", name: "Kenya",          flag: "🇰🇪" },
  { iso: "EG", dial: "+20",  name: "Egypt",          flag: "🇪🇬" },
  { iso: "SA", dial: "+966", name: "Saudi Arabia",   flag: "🇸🇦" },
  { iso: "TR", dial: "+90",  name: "Turkey",         flag: "🇹🇷" },
  { iso: "RU", dial: "+7",   name: "Russia",         flag: "🇷🇺" },
  { iso: "UA", dial: "+380", name: "Ukraine",        flag: "🇺🇦" },
  { iso: "PL", dial: "+48",  name: "Poland",         flag: "🇵🇱" },
  { iso: "SE", dial: "+46",  name: "Sweden",         flag: "🇸🇪" },
  { iso: "NO", dial: "+47",  name: "Norway",         flag: "🇳🇴" },
  { iso: "DK", dial: "+45",  name: "Denmark",        flag: "🇩🇰" },
  { iso: "CH", dial: "+41",  name: "Switzerland",    flag: "🇨🇭" },
  { iso: "IE", dial: "+353", name: "Ireland",        flag: "🇮🇪" },
  { iso: "NZ", dial: "+64",  name: "New Zealand",    flag: "🇳🇿" },
  { iso: "AR", dial: "+54",  name: "Argentina",      flag: "🇦🇷" },
  { iso: "CL", dial: "+56",  name: "Chile",          flag: "🇨🇱" },
  { iso: "CO", dial: "+57",  name: "Colombia",       flag: "🇨🇴" },
  { iso: "CN", dial: "+86",  name: "China",          flag: "🇨🇳" },
  { iso: "HK", dial: "+852", name: "Hong Kong",      flag: "🇭🇰" },
  { iso: "TW", dial: "+886", name: "Taiwan",         flag: "🇹🇼" },
  { iso: "TH", dial: "+66",  name: "Thailand",       flag: "🇹🇭" },
  { iso: "VN", dial: "+84",  name: "Vietnam",        flag: "🇻🇳" },
  { iso: "MY", dial: "+60",  name: "Malaysia",       flag: "🇲🇾" },
];
